### PR TITLE
[wip] Integrate Auth0 login

### PR DESCRIPTION
**Pull request by phjudge**
## Description

This PR mostly follows [the Auth0 Django quick start documentation](https://auth0.com/docs/quickstart/webapp/django/01-login), as adapted by @hancush in [datamade/bga-pensions#5](https://github.com/datamade/bga-pensions/pull/5) to wire up single sign-on. This replaces existing login functionality.

## Auth0 settings

- Application > Allowed callback URLs: http://salary.bettergov.org/complete/auth0/, http://bga-payroll.datamade.us/complete/auth0/, http://localhost:8000/complete/auth0/, http://127.0.0.1:8000/complete/auth0/
- Application > Allowed logout URLs: http://salary.bettergov.org, http://bga-payroll.datamade.us, http://localhost:8000, http://127.0.0.1:8000
- Emails > Templates > Verification Email > Redirect To: {{ application.callback_domain }}/login/auth0

One addition to this PR not covered in bga-pensions: I added configuration to redirect the user to the login view or the sign up view, as described in [python-social-auth](https://python-social-auth-docs.readthedocs.io/en/latest/use_cases.html#pass-custom-get-post-parameters-and-retrieve-them-on-authentication) and [Auth0](https://community.auth0.com/t/passing-initialscreen-to-lock-from-webauth/6906).

### CODE REVIEW

**Comment by phjudge** [comment]
@hancush This covers everything except for the caching. The problem with caching is that I can't use the same template tags because the templates are rendered using jinja2 vs django. I'll defer to your judgement... what's the best course of action here?

**Comment by hancush** [comment]
@phjudge ah, right. also, most of the processing happens in the view code, rather than client side, so the template tags may not be of much use. 

want to take a shot at caching expensive queries in the view code using [django's low-level cache api](https://docs.djangoproject.com/en/2.2/topics/cache/#the-low-level-cache-api)? i've [started roughing out this approach over in pensions](https://github.com/datamade/bga-pensions/blob/79b48393089594fcbcbc6b3331b25e3dd873513f/pensions/views.py#L65), but i'm not yet satisfied with performance. planning to do some work on this today (namely, trying to cache less, cache more, and/or retrieve all the cache objects i need at once rather than in separate queries) – will let you know how it goes.

**Comment by hancush** [comment]
update: making a single query against the cache made the it more performant. here's how i did that: https://github.com/datamade/bga-pensions/pull/19/commits/69d30b0e890704158983b441576b407ced13ff32

**Comment by phjudge** [comment]
@hancush I'll take a crack at it; thanks for your example

**Comment by hancush** [comment]
This was superseded by #340. Do you mind if I close, @phjudge?

**Comment by hancush** [comment]
We decided to go another direction for authentication. Closing this.

**Pull request closed without merging**
