### PR TITLE
Improve download link styling and source data language

### PR DESCRIPTION
**Pull request by smcalilly**
## Overview
Closes issues:
- #565
- #566

## Demo
This includes the new styling + the language change for the source data:
Screen Shot 2021-11-16 at 11 21 46 AM

## Testing
- pull down `download-links` branch
- test links and make sure they look good

### CODE REVIEW

**Review by fgregg — CHANGES_REQUESTED** [review]
Looks nice on desktop! Looks a bit cramped on a narrow viewport.


Screenshot 2021-11-16 at 12-42-46 Cook County SD 130

i think you could either

1. do a vertical stack if viewport is narrow
2. disable the download button on narrow viewports. probably not a lot of utility for people downloading CSVs on their phones.

**Comment by smcalilly** [comment]
@fgregg my first instinct is to do a vertical stack, how does this look? i can hide on mobile if you think that's the right thing to do.
Screen Shot 2021-11-16 at 11 51 01 AM

**Comment by fgregg** [comment]
I think the vertical is okay, but the differential weight of "Download Data" doesn't seem right for this viewport. It looks like it's the most important thing, and what you probably want to do.

Can you try reducing the weight for smaller viewports?

**Comment by smcalilly** [comment]
@fgregg something like this?
Screen Shot 2021-11-16 at 12 17 19 PM

**Comment by fgregg** [comment]
Looks great!

**Review by fgregg — APPROVED** [review]

**Pull request merged**
